### ISSUE TITLE
Blank site

### ISSUE THREAD

**Issue by Sega01** [dreerr/TemplateEnginePug#1]
Hi, thanks for the update from jade to the pug libary.
But i have a problem with that module. When i just installed the new module and tried to use my old jade code with it, im getting a blank page without an error code.

After it, to reduce stupids mistakes, i installed a second blank processwire page with just the TemplateEngineFactory and TemplateEnginePug modules and copied your example code from here (https://processwire.com/talk/topic/11386-module-pug-for-the-templateenginefactory/) into the home.pug in templates/views. But im still getting only a blank white page without any content. 
Do you know where the error could be?

**Comment by dreerr** [comment]
I've now included the Pug repository, this would have to be done manually because GitHub does not download Submodules directly. Version is increased, so you can download the new version with Processwire directly.
