### ISSUE TITLE
Compile Error: require_once()

### ISSUE THREAD

**Issue by nickngqs** [dreerr/TemplateEnginePug#2]
I'm receiving an error of 
```
Compile Error: require_once(): Failed opening required '../TemplateEngine.php' (include_path='.:') (line 17 of .../site/modules/TemplateEnginePug-master/TemplateEnginePug.module) 
```

**Comment by nickngqs** [comment]
Ok found the issue i have to name the folder for TemplateEngineFactory as TemplateEngineFactory

**Comment by dreerr** [comment]
Hey Nick,
Let me know if you find anything else! Error reporting could be better, I'm trying to correct that…

**Comment by nickngqs** [comment]
The module requires TemplateEngineFactory as pre-installed. But it assumes that the folder for the TemplateEngineFactory is called TemplateEngineFactory. I was extracting TemplateEngineFactory straight up from a zip file, and it's usually TemplateEngineFactory-master. So I'll just need to rename it.
