### ISSUE TITLE
Compatibility with TemplateEngineFactory 2.x

### ISSUE THREAD

**Issue by wanze** [dreerr/TemplateEnginePug#3]
Hi @dreerr 

Just wanted to let you know that I have released a new major version `2.x` for the TemplateEngineFactory module. The new version uses a slightly different approach on how modules register a template engine to the factory. However, the update is easy. If you are interested to release a `2.x` version of TemplateEnginePug, here are some useful links

* Some information about the `2.0` release of the factory in the [forums](https://processwire.com/talk/topic/6833-module-templateenginefactory/?do=findComment&comment=180672).
* How to implement a template engine in the [documentation](https://github.com/wanze/TemplateEngineFactory/blob/master/DOCUMENTATION.md#implementing-a-template-engine).
* For an example, you can check the new [TemplateEngineTwig](https://github.com/wanze/TemplateEngineTwig) implementation.

Note: Version `1.x` of the factory continues to exist, it is available in the `1.x` branch of the module.

Cheers

**Comment by dreerr** [comment]
Dear wanze, 
I shamelessly copied the majority of the TwigTemplateEngine, should be 2.x complaint now!

**Comment by wanze** [comment]
Looks good, copy + paste is the way to go :) The only thing missing is a `v2.0.0` release on GitHub, in order to install via composer. See: https://github.com/wanze/TemplateEngineTwig/releases

Cheers

**Comment by dreerr** [comment]
Thanks, done!
